[package]
name = "lazyprop"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = "0.19.0"
crossterm = "0.28.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.33"
config = "0.14.0"
anyhow = "1.0.94"
thiserror = "2.0.5"
